#### Package import ####
library("R.matlab")
library("astrochron")
library("lattice")
library("palinsol")

#### Utility function import ####
# needed to generate insolated driven SL
source("src/R/utils.R")

#### Constants ####

time_increment_myr = 0.001 # temporal res
timespan_obs_myr = 2.58 # duration of obs
start_obs_myr_bp = 2.58 # whole Pleistocene
grid_point_dist_km = 0.1 # res. of CarboCATLite
sampling_freq_m = 0.05 # res of strat. columns

# maximum amplitude of sl curves
max_amp_m_1 = 2 
max_amp_m_2 = 20

# min & max freq examined in depth domain
min_freq = 0.01
max_freq = 10

#### Generate Sea Level Curves ####
ins_sl_2m_amp = ins_to_sl(
  from = start_obs_myr_bp,
  to = start_obs_myr_bp - timespan_obs_myr,
  by = time_increment_myr,
  max_ampl = max_amp_m_1
)
ins_sl_20m_amp = ins_to_sl(
  from = start_obs_myr_bp,
  to = start_obs_myr_bp - timespan_obs_myr,
  by = time_increment_myr,
  max_ampl = max_amp_m_2
)

write.table(ins_sl_2m_amp$y, file = "data/r_outputs/ins_sl_2m_amp.txt", row.names = FALSE, col.names = FALSE)
write.table(ins_sl_20m_amp$y, file = "data/r_outputs/ins_sl_20m_amp.txt", row.names = FALSE, col.names = FALSE)

#### Import data generated by CarboCATLite ####
matlab_raw_data <- R.matlab::readMat("data/matlab_outputs/bathurst_2m_and_20m_amp_adm.mat")

time = matlab_raw_data$bathurst.20m.amp.time[1,]
time = time[time <= timespan_obs_myr]
dist_from_shore_km = seq_len(nrow(matlab_raw_data$bathurst.20m.amp.adm.along.dip)) * grid_point_dist_km

#### Process 20 m ampl scenario ####
res_list = list()
for ( i in seq_along(dist_from_shore_km)){
  li = list()
  li[["height"]] = matlab_raw_data$bathurst.20m.amp.adm.along.dip[i,][seq_along(time)]
  li[["dist_from_shore_km"]]  = paste0(dist_from_shore_km[i], " km")
  res_list[[i]] = li
  res_list[[i]][["completeness"]] = 1 - sum(duplicated(res_list[[i]]$height))/length(time)
}

lith_vals = rep(c(1,0), length(time)) # code lithologies with 0 and 1
for (i in seq_along(res_list)){
  res_list[[i]][["bed_bdries"]] = unique(res_list[[i]]$height[duplicated(res_list[[i]]$height)])
} 

#### cyclostrat analysis ####
for (i in seq_along(res_list)){
  loc = seq(from = 0, to = max(res_list[[i]]$bed_bdries), by = sampling_freq_m)
  val = approx(x = res_list[[i]]$bed_bdries,
                     y = lith_vals[1:length(res_list[[i]]$bed_bdries)],
                     method = "constant",
                     xout = loc)$y
  res_list[[i]][["df"]] = data.frame(loc,val)
  res_list[[i]][["mtm"]] = astrochron::mtm(dat = res_list[[i]][["df"]],
                               pl = 3, output = 1, genplot = FALSE, verbose = FALSE)
}


#### Figures ####
make_completeness_fig = function(){
  pdf(file = "figs/completeness.pdf")
  compl = sapply(seq_along(dist_from_shore_km), function(x) res_list[[x]]$completeness)
  plot(x = dist_from_shore_km,
       y = compl * 100, 
       type = "l",
       ylim = c(0,100),
       lwd = 3)
  
  dev.off()
}


  freq_interp = 10^seq(log10(min_freq), log10(max_freq), by = 0.1)
  mat = matrix(data = NA,
               nrow = 150,
               ncol = length(freq_interp))
  for (i in 1:150){
    aa = approx(x = res_list[[i]]$mtm$Frequency, y = res_list[[i]]$mtm$Power, xout = freq_interp)$y
    mat[i,] = aa
  }
  
  pdf(file = "./figs/power.pdf")
  lattice::levelplot(log10(mat))
  dev.off()


make_sl_plot = function(){
  pdf("figs/sl.pdf")
  plot(x = ins_sl_20m_amp$x,
       y = ins_sl_20m_amp$y,
       type = "l",
       lwd = 3,
       col = "blue",
       ylab = "Eustatic Sea Level [m]",
       xlab = "Time [Myr]")
  dev.off()
}

make_sl_spectrum_plot = function(){
  pdf("figs/sl_spectrum.pdf")
  mtm(ins_sl_20m_amp, verbose = FALSE, pl = 3)
  dev.off()
}

make_sl_spectrum_plot()
make_sl_plot()
make_completeness_fig()
make_power_spec_plot()


## plot expected frequency of significant frequencies in time domain
signif_freq = mtm(ins_sl_20m_amp, verbose = FALSE, pl = 3,output = 3,genplot = FALSE)$Frequency

height = sapply(seq_along(dist_from_shore_km), function(x) max(res_list[[x]]$height))
plot(NULL,
     ylim = log10(c(min_freq, max_freq)), 
     xlim = range(dist_from_shore_km))
#signif_freq = c(25, 50)
lwd = 3
#cols = c("red", "blue")
for (i in seq_along(signif_freq)){
  cycles_in_obs_time = signif_freq[i] * timespan_obs_myr
  cycles_per_height = cycles_in_obs_time / height
  lines(dist_from_shore_km, log10(cycles_per_height), lwd = lwd)
}
#legend("topleft", col = cols, lwd = 3, legend = c("20 kyr cycle", "10 kyr cycle"))
